---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./
    enforce_order: False
  dnsimple:
    class: octodns_dnsimple.DnsimpleProvider
    token: env/DNSIMPLE_API_KEY
    account: env/DNSIMPLE_ACCOUNT_NUMBER
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN

zones:
  hackclub.com.:
    sources:
      - config
    targets:
      - dnsimple
  hackclub.org.:
    sources:
      - config
    targets:
      - dnsimple
  hackclub.io.:
    sources:
      - config
    targets:
      - dnsimple
  hackedu.us.:
    sources:
      - config
    targets:
      - dnsimple
  hack.af.:
    sources:
      - config
    targets:
      - dnsimple
  bulckcah.com.:
    sources:
      - config
    targets:
      - dnsimple
  dino.icu.:
    sources:
      - config
    targets:
      - dnsimple
  dinosaurbbq.org.:
    sources:
      - config
    targets:
      - dnsimple
  hackclub.app.:
    sources:
      - config
    targets:
      - dnsimple
  hackfoundation.org.:
    sources:
      - config
    targets:
      - dnsimple
  wackclub.com.:
    sources:
      - config
    targets:
      - dnsimple
  bank.engineering.:
    sources:
      - config
    targets:
      - dnsimple
  scrap.dev.:
    sources:
      - config
    targets:
      - dnsimple
  scrapbook.dev.:
    sources:
      - config
    targets:
      - dnsimple
  hcb.gg.:
    sources:
      - config
    targets:
      - cloudflare
